apiVersion: app/v1
kind: Deployment
metadata:
  name: finance_tracker
spec:
  replicas: 1
  selector: 
    matchlables:
    app: finance_tracker
  templates:
    metadata:
      lables:
        app: finance_tracker
      spec:
        containers:
           
