apiVersion: v1
kind: Secret
metadata:
  name: expense-tracker-secrets
type: Opaque
stringData:
  postgres-password: "root" 
  CLIENT_SECRET: "jpKp-Kvq7ckHxkfqe5oHOvIZLhA9QsN52DaSWC-O4mN_UqtyZTOuuUtfxb4svyfa"